services:
  nzbdav:
    image: ghcr.io/nzbdav-dev/nzbdav
    container_name: nzbdav
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /opt/appdata/nzbdav:/config
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - VERSION=latest
    volumes:
      - /opt/appdata/plex:/config
      - nzbdav:/mnt/nzbdav
      - /mnt/data:/data
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /opt/appdata/prowlarr:/config
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /opt/appdata/radarr:/config
      - nzbdav:/mnt/nzbdav
      - /mnt/data:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "radarr-vps"
      tsdproxy.container_port: 7878
      tsdproxy.ephemeral: "false"
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /storage/appdata/sonarr:/config
      - nzbdav:/mnt/nzbdav
      - /mnt/data:/data
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - URL=boxer.haus
      - SUBDOMAINS=nzbdav,radarr,plex
      - VALIDATION=http
    volumes:
      - /opt/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /opt/appdata/tsdproxy:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tsdproxy"
      tsdproxy.container_port: 8080
      tsdproxy.ephemeral: "false"
    restart: unless-stopped
volumes:
  datadir:
  nzbdav:
    driver: rclone
    driver_opts:
      remote: 'nzb-dav:'
      allow_other: 'true'
      vfs_cache_mode: off
      dir_cache_time: 1s
      allow_non_empty: 'true'
      uid: 1000
      gid: 1000
